services:
  postgres:
    container_name: postgres-event
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "event"
    networks:
      - networkProduct
  pgadmin:
    container_name: pgadmin-event
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - networkProduct
  redis:
    container_name: redis-event
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  #Interface Gráfica do Usuário (GUI)
  redis-commander:
    container_name: redis-commander-event
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
networks:
  networkProduct:
    driver: bridge